<?php

/**
 * Implements hook_theme().
 */

function display_time_theme($existing, $type, $theme, $path) {
  return array('display_time_template' =>                  // this is the name of the template
           array(
            'variables' => array(
                'country' => 'Default country',
                'city' => 'Default city',
               'time'=>'time',
            ),
        )
    );
}